name: BackPack-Plugin
version: ${project.version}
main: me.modione.backpackplugin.main.BackPackPlugin
api-version: 1.16
commands:
  bpsettings:
    description: The setings for this plugin

permissions:
  bp.settings:
    description: settings...
    default: op